edition = "2021"

unstable_features = true

indent_style = "Block"

reorder_imports = true
reorder_impl_items = true
imports_granularity="Crate"

struct_field_align_threshold = 20
enum_discrim_align_threshold = 20

use_field_init_shorthand = true
overflow_delimited_expr = false