[package]
name = "jassparse"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
case = "1.0.0"
clap = { version = "4.3.17", features = ["derive"] }
pest = "2.7.1"
pest_derive = "2.7.1"
